apiVersion: v1

kind: ResourceQuota

metadata:
  namespace: jawza-tawazun

  name: day2-exam

spec:

  hard:

    requests.cpu: "2"

    requests.memory: 2Gi

    limits.cpu: "4"

    limits.memory: 4Gi
                                                                                                                                                                                    